### ISSUE TITLE
Can't run Set-AzSDKAlerts on v 2.6.1

### ISSUE THREAD

**Issue by CtrlDot** [azsdk/azsdk-docs#43]
Hi Team,

I am trying to run the Set-AzSDKAlerts on my subscription, and am getting the following error:

> The property 'AlertList' cannot be found on this object. Verify that the property exists.

I have tried the troubleshooting steps on the main page, but since this isn't a result of the an AzureRM call, I don't think this is related to a version mismatch.

I've also confirmed that I am running the correct version of powershell.

Offending code (based on the error message)

	Alerts([string] $subscriptionId, [InvocationInfo] $invocationContext, [string] $tags): 
        Base($subscriptionId, $invocationContext)
    {
		$this.V1AlertRGName = [Constants]::V1AlertRGName
		$this.ResourceGroup = [ConfigurationManager]::GetAzSdkConfigData().AzSDKRGName
		$this.AlertPolicyObj =  $this.LoadServerConfigFile("Subscription.InsARMAlerts.json");
		$this.Policy = $this.AlertPolicyObj.AlertList
		$this.FilterTags = $this.ConvertToStringArray($tags);
	}

**Comment by sbyna-msft** [comment]
@CtrlDot Thanks for reaching out. Please try once now. You can just re-run the command. There was an encoding error in our config file which was resulting in parse issue. Do let us know if you are still facing the issue.
