### ISSUE TITLE
[Question] Why is it advised to run PowerShell non-elevated during setup?

### ISSUE THREAD

**Issue by Stijnc** [azsdk/azsdk-docs#65]
The [setup documentation](https://github.com/azsdk/azsdk-docs/tree/master/00a-Setup) uses the currentuser scope and the [FAQ](https://github.com/azsdk/azsdk-docs/tree/master/00a-Setup#should-i-run-powershell-ise-as-administrator-or-regular-user) also advises against running PowerShell elevated.

From my point of view this does not really make sense, especially of you would like to schedule the execution or use the module on your build agents. 
During execution a system account (vsts build agents for example) is mostly used and a system wide availability of the module and its prerequisites makes a lot of sense (or is even required).

**Comment by mprabhu11** [comment]
The 'CurrentUser' recommendation applies when you run AzSDK locally to perform scans from PS. The point is that we don't perform *any* task on the user's machine that requires elevated privilege. Thus just from a security best practice standpoint, it makes sense to run as 'CurrentUser' for the typical/manual scan use cases.
